### ISSUE TITLE
Cannot detach netvm while windows-mgmt is running

### ISSUE THREAD

**Issue by brendanhoar** [elliotkillick/qvm-create-windows-qube#4]
After "Air gapping windows-mgmt..." an error is thrown:
"qvm-prefs: error: no such property: 'netvm'

This error is misleading (see: https://github.com/QubesOS/qubes-issues/issues/3528 ) - what is really happening is that the netvm cannot be detached while windows-mgmt is running.

```
Jan 13 23:40:52 dom0 libvirtd[2785]: 2020-01-14 04:40:52.357+0000: 2816: error : libxlDomainDetachNetDevice:3984 : internal error: libxenlight failed to detach network device
Jan 13 23:40:52 dom0 qubesd[2756]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.property.Set' dest=b'windows-mgmt' arg=b'netvm' len(untrusted_payload)=0
Jan 13 23:40:52 dom0 qubesd[2756]: Traceback (most recent call last):
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 275, in respond
Jan 13 23:40:52 dom0 qubesd[2756]:     untrusted_payload=untrusted_payload)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Jan 13 23:40:52 dom0 qubesd[2756]:     yield self  # This tells Task to wait for completion.
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Jan 13 23:40:52 dom0 qubesd[2756]:     future.result()
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Jan 13 23:40:52 dom0 qubesd[2756]:     raise self._exception
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Jan 13 23:40:52 dom0 qubesd[2756]:     result = coro.send(None)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
Jan 13 23:40:52 dom0 qubesd[2756]:     res = func(*args, **kw)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 244, in vm_property_set
Jan 13 23:40:52 dom0 qubesd[2756]:     untrusted_payload=untrusted_payload)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 264, in _property_set
Jan 13 23:40:52 dom0 qubesd[2756]:     setattr(dest, self.arg, newvalue)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/vm/__init__.py", line 460, in __set__
Jan 13 23:40:52 dom0 qubesd[2756]:     super(VMProperty, self).__set__(instance, value)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/__init__.py", line 261, in __set__
Jan 13 23:40:52 dom0 qubesd[2756]:     name=self.__name__, newvalue=value, oldvalue=oldvalue)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 198, in fire_event
Jan 13 23:40:52 dom0 qubesd[2756]:     pre_event=pre_event)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 166, in _fire_event
Jan 13 23:40:52 dom0 qubesd[2756]:     effect = func(self, event, **kwargs)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/vm/mix/net.py", line 430, in on_property_pre_set_netvm
Jan 13 23:40:52 dom0 qubesd[2756]:     self.detach_network()
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/vm/mix/net.py", line 338, in detach_network
Jan 13 23:40:52 dom0 qubesd[2756]:     vm=self))
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 101, in wrapper
Jan 13 23:40:52 dom0 qubesd[2756]:     return attr(*args, **kwargs)
Jan 13 23:40:52 dom0 qubesd[2756]:   File "/usr/lib64/python3.5/site-packages/libvirt.py", line 1170, in detachDevice
Jan 13 23:40:52 dom0 qubesd[2756]:     if ret == -1: raise libvirtError ('virDomainDetachDevice() failed', dom=self)
Jan 13 23:40:52 dom0 qubesd[2756]: libvirt.libvirtError: internal error: libxenlight failed to detach network device
```

Proposed solution: issue shutdown command to windows-mgmt VM first, validate shutdown, then continue.

B

**Comment by elliotkillick** [comment]
Changes merged. Cheers Brendan!
